<?php

const HOMEPAGE_INTRO_POST_ID = 85;
const HOMEPAGE_HISTORY_POST_ID = 86;
const HOMEPAGE_CONTACT_COMPLETE_POST_ID = 338;

const GARYU_MAIL_TO_ADMIN_POST_ID = 226;
const GARYU_MAIL_TO_USER_POST_ID = 227;

const GARYU_NEWS_PER_PAGE = 10;

const LOCALE_JAPAN = 'ja';
const LOCALE_EN = 'en';
const LOCALE_HU = 'hu';
const DEFAULT_LOCALE = LOCALE_JAPAN;
const SUPPORT_LOCALES = array(LOCALE_JAPAN, LOCALE_EN, LOCALE_HU);

const GARYU_GALLERY_POST_TYPE = 'gallery';
const GARYU_COMPANY_POST_TYPE = 'company';
const GARYU_HOMEPAGE_POST_TYPE = 'homepage';
const GARYU_PARTNER_COMPANY_POST_TYPE = 'partner';
const GARYU_NEWS_POST_TYPE = 'news';
const GARYU_MAIL_POST_TYPE = 'mail';

const GARYU_POST_TYPES = array(GARYU_GALLERY_POST_TYPE, 
				GARYU_COMPANY_POST_TYPE, GARYU_HOMEPAGE_POST_TYPE, 
				GARYU_PARTNER_COMPANY_POST_TYPE, GARYU_NEWS_POST_TYPE, GARYU_MAIL_POST_TYPE);

const GARYU_NOT_ALLOW_DELETE_AND_CREATE_POST_TYPES = array(GARYU_HOMEPAGE_POST_TYPE, GARYU_MAIL_POST_TYPE);

const GARYU_ADMIN_MAIL = 'congmt@v-job.co.jp';